import os
import json
from pathlib import Path
from dotenv import load_dotenv

from openai import OpenAI
from dotenv import load_dotenv

from test_generator.rule_based_generator import (
    get_expected_success_status
)


# Load the .env file from agent_backend
BACKEND_ROOT = Path(__file__).resolve().parents[2]
load_dotenv(BACKEND_ROOT / ".env")

# NVIDIA client
client = OpenAI(
    api_key=os.getenv("NVIDIA_API_KEY"),
    base_url="https://integrate.api.nvidia.com/v1",
    timeout=120.0,
    max_retries=2
)

NVIDIA_MODEL = "openai/gpt-oss-20b"



def generate_ai_tests(api_info):

    prompt = f"""
You are an expert API security and software tester.

Generate exactly 5 intelligent test cases for this API endpoint.

Endpoint:
{api_info["path"]}

Method:
{api_info["method"]}

Request body schema:
{json.dumps(api_info.get("request_body"), indent=2)}

Generate tests focusing on:

1. Boundary values
2. Edge cases
3. Unusual but valid inputs
4. Very large or very small values
5. Special characters
6. Interesting combinations of inputs

Do NOT generate:
- Missing required fields
- Basic wrong data types
- Basic null tests

Those tests are already generated by the rule-based test generator.

Return ONLY valid JSON.

Use exactly this format:

{{
    "tests": [
        {{
            "category": "boundary",
            "description": "Description of the test",
            "request": {{
                "body": {{}}
            }}
        }}
    ]
}}

The "tests" array must contain exactly 5 test cases.

Do not add any text outside the JSON object.
"""

    # Try up to 3 times
    for attempt in range(1, 4):

        print(
            f"[AI Generator] Attempt {attempt}/3"
        )

        try:

            print(
                f"[AI Generator] Calling NVIDIA API "
                f"(model: {NVIDIA_MODEL})..."
            )

            response = client.chat.completions.create(
                timeout=120,
                model=NVIDIA_MODEL,
                messages=[
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0.2,
                max_tokens=4000,
                response_format={
                    "type": "json_object"
                }
            )

            message = response.choices[0].message

            response_text = (
                message.content or ""
            ).strip()

            if (
                not response_text
                and getattr(
                    message,
                    "reasoning_content",
                    None
                )
            ):
                response_text = (
                    message.reasoning_content.strip()
                )

            print(
                "[AI Generator] Response received."
            )

            if not response_text:
                raise ValueError(
                    "Empty response from NVIDIA API"
                )

            # Remove markdown code fences
            if response_text.startswith("```"):
                response_text = (
                    response_text
                    .replace("```json", "")
                    .replace("```", "")
                    .strip()
                )

            # Find JSON object
            start = response_text.find("{")
            end = response_text.rfind("}")

            if start == -1 or end == -1:
                raise ValueError(
                    "No JSON object found"
                )

            json_text = response_text[
                start:end + 1
            ]

            data = json.loads(json_text)

            tests = data["tests"]

            if not isinstance(tests, list):
                raise ValueError(
                    "'tests' must be a list"
                )

            if len(tests) != 5:
                raise ValueError(
                    f"AI returned {len(tests)} "
                    f"tests instead of exactly 5"
                )

            # Validate each test
            for test in tests:

                if "category" not in test:
                    raise ValueError(
                        "AI test missing category"
                    )

                if "description" not in test:
                    raise ValueError(
                        "AI test missing description"
                    )

                if "request" not in test:
                    raise ValueError(
                        "AI test missing request"
                    )

            print(
                "[AI Generator] Successfully generated "
                "5 AI tests."
            )

            ai_tests = []

            for test in tests:

                ai_tests.append({
                    "endpoint": api_info["path"],
                    "method": api_info["method"],
                    "category": test["category"],
                    "description": test["description"],
                    "request": test["request"],
                    "expected": {
                        "status_code":
                            get_expected_success_status(
                                api_info
                            )
                    }
                })

            return ai_tests

        except Exception as e:

            print(
                f"[AI Generator] Attempt {attempt} failed: "
                f"{e}"
            )

            if attempt < 3:
                print(
                    "[AI Generator] Retrying..."
                )
            else:
                print(
                    "[AI Generator] All 3 attempts failed."
                )

    return []